# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44148b11b0f3e2c79b76bb3287511b4be993d736a4def09dd0f4382b973c22b0409077106552f0b6aa5dcf62c1362e4e607b30451fcf6e942982ee39c4bb1335

test:
  secret_key_base: 93dbb07504e70b874de7f0e3c0fe2a2791c6a252a8e327f283f2dfb9172f410846146f2de2f234a12d9f9adc9f06a6202756701a146d939065bd5fc00716e8b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
